### PR TITLE
ops: fix test agg fields 

### LINKED ISSUE #565: [ai4realnet] fully scored submission shown as not completely scored
### Please agree to the following

- [x] I have searched [existing issues](https://github.com/flatland-association/flatland-benchmarks/issues?q=) for duplicates
- [x] I agree to follow this project's [Code of Conduct](https://github.com/flatland-association/flatland-benchmarks/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

[ai4realnet] fully scored submission shown as not completely scored

### System Setup

```markdown
https://ai4realnet.flatland.cloud/suites/0ca46887-897a-463f-bf83-c6cd6269a977/3b1bdca6-ed90-4938-bd63-fd657aa7dcd7/submissions/26e4ce43-ca39-463e-b8f1-393e881784ec
```

### Steps to Reproduce

https://ai4realnet.flatland.cloud/suites/0ca46887-897a-463f-bf83-c6cd6269a977/3b1bdca6-ed90-4938-bd63-fd657aa7dcd7/submissions/26e4ce43-ca39-463e-b8f1-393e881784ec

### Expected Behavior

Should be publishable/shown completely scored

### Actual Behavior

Shown as "not completely scored"

### Reproducibility

Always

### Relevant Log Output

```shell

```

### Anything else?

Image

### PR DESCRIPTION
**Pull request by chenkins**
## Changes
* fix test agg fields (tests only have one field "primary" or "punctuality", which is aggregated from the same field in all scenarios). If test were to have multiple fields, then they would have to go under TEST_FIELDS.

## Related issues
Closes #565 

## Request for Comment

* Risk: 
* Discussion: 

## Checklist

- [ ] Tests are included for relevant behavior changes.
- [ ] Prefix the commits with one of the labels of [Conventional Commit messages](https://www.conventionalcommits.org/en/v1.0.0/).

- [ ] Document changes in this pull request above.
- [ ] Documentation is added in the `docs` folder for relevant behavior changes.
- [ ] Technical guidelines listed in `docs/CONTRIBUTING.md` are followed.

### CODE REVIEW

File: definitions/ai4realnet/ai4realnet_definitions.sql [hunk 1]
```diff
@@ -9220,8 +9231,8 @@ INSERT INTO tests
 
 INSERT INTO fields
         (id, key, description, agg_func, agg_fields)
-        VALUES ('e248e90c-65e0-4e36-89df-2e3232ed430d', 'primary', 'Test score (MEAN of scenario scores)', 'MEAN', '["primary"]')
-        ON CONFLICT(id) DO UPDATE SET key=EXCLUDED.key, description=EXCLUDED.description, agg_func=EXCLUDED.agg_func, agg_weights=EXCLUDED.agg_weights;
+VALUES ('e248e90c-65e0-4e36-89df-2e3232ed430d', 'primary', 'Test score (MEAN of scenario scores)', 'MEAN', '"primary"') ON CONFLICT(id) DO
+ UPDATE SET key =EXCLUDED.key, description=EXCLUDED.description, agg_func=EXCLUDED.agg_func, agg_fields=EXCLUDED.agg_fields;
```
Comment (chenkins) [inline definitions/ai4realnet/ai4realnet_definitions.sql]: unnecessary diff
